import type { Metadata } from 'next';
import { Mulish, Montserrat_Alternates, Indie_Flower } from 'next/font/google';
import './globals.scss';
import Header from '@/components/Header/Header';
import styles from './page.module.scss';
import Footer from '@/components/Footer/Footer';
import MainTitle from '@/components/MainTitle/MainTitle';
import ReduxProvider from '@/utils/ReduxProvider';
import { AuthContextProvider } from '@/hooks/useAuth';
import ScrollToTopOnRouteChange from '@/utils/ScrollToTopOnRouteChange';
import { Toaster } from 'sonner';

const mulish = Mulish({
	variable: '--font-mulish',
	subsets: ['latin', 'cyrillic'],
	weight: ['400', '500', '600'],
});

const montserrat_Alternates = Montserrat_Alternates({
	variable: '--font-montserrat-alternates',
	subsets: ['latin', 'cyrillic'],
	weight: ['400', '500', '600'],
});

const indie_Flower = Indie_Flower({
	variable: '--font-indie-flower',
	subsets: ['latin'],
	weight: ['400'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${mulish.variable} ${montserrat_Alternates.variable} ${indie_Flower.variable}`}
			>
				<div className={styles.layoutContainer}>
					<ReduxProvider>
						<AuthContextProvider>
							<Header />
							<MainTitle />
							<main className={styles.main}>{children}</main>
							<Footer />
						</AuthContextProvider>
					</ReduxProvider>
				</div>
				<ScrollToTopOnRouteChange />
				<Toaster duration={2500} />
			</body>
		</html>
	);
}
